services:
  app:
    image: flash-action:1.0.0
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: docker
      PG_HOST: db
      DATABASE_URL: postgres://mypostgresuser:mysecretpassword@db:5433/auction
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:18.3-alpine3.23
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: mypostgresuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: auction

    volumes:
      - postgres-data:/var/lib/postgresql/data

    command: -p 5433

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
