/**
 * ~100 users for testing
 * */
export const userData = [
  {
    email: 'ljuba@ljuba.com',
    username: 'ljuba',
    password: 'ljuba',
  },
  {
    email: 'admin@example.com',
    username: 'admin',
    password: 'admin',
  },
  {
    email: 'user@example.com',
    username: 'user',
    password: 'user',
  },
  {
    email: 'john.smith@example.com',
    username: 'johnsmith',
    password: 'password123',
  },
  {
    email: 'sarah.johnson@example.com',
    username: 'sarahj',
    password: 'secure456',
  },
  {
    email: 'michael.brown@example.com',
    username: 'mikebrown',
    password: 'mypass789',
  },
  {
    email: 'emily.davis@example.com',
    username: 'emilyd',
    password: 'emily2024',
  },
  {
    email: 'david.wilson@example.com',
    username: 'davidw',
    password: 'wilson123',
  },
  {
    email: 'jennifer.martinez@example.com',
    username: 'jenniferm',
    password: 'jenny456',
  },
  {
    email: 'robert.anderson@example.com',
    username: 'roberta',
    password: 'robert789',
  },
  {
    email: 'lisa.taylor@example.com',
    username: 'lisat',
    password: 'taylor123',
  },
  {
    email: 'james.thomas@example.com',
    username: 'jamest',
    password: 'james456',
  },
  {
    email: 'mary.jackson@example.com',
    username: 'maryj',
    password: 'mary789',
  },
  {
    email: 'william.white@example.com',
    username: 'williamw',
    password: 'white123',
  },
  {
    email: 'patricia.harris@example.com',
    username: 'patriciah',
    password: 'patricia456',
  },
  {
    email: 'charles.martin@example.com',
    username: 'charlesm',
    password: 'charles789',
  },
  {
    email: 'linda.thompson@example.com',
    username: 'lindat',
    password: 'linda123',
  },
  {
    email: 'thomas.garcia@example.com',
    username: 'thomasg',
    password: 'garcia456',
  },
  {
    email: 'barbara.martinez@example.com',
    username: 'barbaram',
    password: 'barbara789',
  },
  {
    email: 'christopher.robinson@example.com',
    username: 'chrisr',
    password: 'chris123',
  },
  {
    email: 'susan.clark@example.com',
    username: 'susanc',
    password: 'susan456',
  },
  {
    email: 'daniel.rodriguez@example.com',
    username: 'danielr',
    password: 'daniel789',
  },
  {
    email: 'jessica.lewis@example.com',
    username: 'jessical',
    password: 'jessica123',
  },
  {
    email: 'matthew.lee@example.com',
    username: 'matthewl',
    password: 'matthew456',
  },
  {
    email: 'karen.walker@example.com',
    username: 'karenw',
    password: 'karen789',
  },
  {
    email: 'anthony.hall@example.com',
    username: 'anthonyh',
    password: 'anthony123',
  },
  {
    email: 'nancy.allen@example.com',
    username: 'nancya',
    password: 'nancy456',
  },
  {
    email: 'mark.young@example.com',
    username: 'marky',
    password: 'mark789',
  },
  {
    email: 'betty.hernandez@example.com',
    username: 'bettyh',
    password: 'betty123',
  },
  {
    email: 'donald.king@example.com',
    username: 'donaldk',
    password: 'donald456',
  },
  {
    email: 'helen.wright@example.com',
    username: 'helenw',
    password: 'helen789',
  },
  {
    email: 'paul.lopez@example.com',
    username: 'paull',
    password: 'paul123',
  },
  {
    email: 'sandra.hill@example.com',
    username: 'sandrah',
    password: 'sandra456',
  },
  {
    email: 'steven.scott@example.com',
    username: 'stevens',
    password: 'steven789',
  },
  {
    email: 'ashley.green@example.com',
    username: 'ashleyg',
    password: 'ashley123',
  },
  {
    email: 'kenneth.adams@example.com',
    username: 'kennetha',
    password: 'kenneth456',
  },
  {
    email: 'kimberly.baker@example.com',
    username: 'kimberlyb',
    password: 'kimberly789',
  },
  {
    email: 'andrew.gonzalez@example.com',
    username: 'andrewg',
    password: 'andrew123',
  },
  {
    email: 'donna.nelson@example.com',
    username: 'donnan',
    password: 'donna456',
  },
  {
    email: 'joshua.carter@example.com',
    username: 'joshuac',
    password: 'joshua789',
  },
  {
    email: 'carol.mitchell@example.com',
    username: 'carolm',
    password: 'carol123',
  },
  {
    email: 'brian.perez@example.com',
    username: 'brianp',
    password: 'brian456',
  },
  {
    email: 'michelle.roberts@example.com',
    username: 'micheller',
    password: 'michelle789',
  },
  {
    email: 'kevin.turner@example.com',
    username: 'kevint',
    password: 'kevin123',
  },
  {
    email: 'amanda.phillips@example.com',
    username: 'amandap',
    password: 'amanda456',
  },
  {
    email: 'george.campbell@example.com',
    username: 'georgec',
    password: 'george789',
  },
  {
    email: 'melissa.parker@example.com',
    username: 'melissap',
    password: 'melissa123',
  },
  {
    email: 'edward.evans@example.com',
    username: 'edwarde',
    password: 'edward456',
  },
  {
    email: 'deborah.edwards@example.com',
    username: 'deborahe',
    password: 'deborah789',
  },
  {
    email: 'timothy.collins@example.com',
    username: 'timothyc',
    password: 'timothy123',
  },
  {
    email: 'stephanie.stewart@example.com',
    username: 'stephanies',
    password: 'stephanie456',
  },
  {
    email: 'ronald.sanchez@example.com',
    username: 'ronalds',
    password: 'ronald789',
  },
  {
    email: 'rebecca.morris@example.com',
    username: 'rebeccam',
    password: 'rebecca123',
  },
  {
    email: 'jeffrey.rogers@example.com',
    username: 'jeffreyr',
    password: 'jeffrey456',
  },
  {
    email: 'laura.reed@example.com',
    username: 'laurar',
    password: 'laura789',
  },
  {
    email: 'ryan.cook@example.com',
    username: 'ryanc',
    password: 'ryan123',
  },
  {
    email: 'sharon.morgan@example.com',
    username: 'sharonm',
    password: 'sharon456',
  },
  {
    email: 'jacob.bell@example.com',
    username: 'jacobb',
    password: 'jacob789',
  },
  {
    email: 'cynthia.murphy@example.com',
    username: 'cynthiam',
    password: 'cynthia123',
  },
  {
    email: 'gary.bailey@example.com',
    username: 'garyb',
    password: 'gary456',
  },
  {
    email: 'kathleen.rivera@example.com',
    username: 'kathleenr',
    password: 'kathleen789',
  },
  {
    email: 'nicholas.cooper@example.com',
    username: 'nicholasc',
    password: 'nicholas123',
  },
  {
    email: 'amy.richardson@example.com',
    username: 'amyr',
    password: 'amy456',
  },
  {
    email: 'eric.cox@example.com',
    username: 'ericc',
    password: 'eric789',
  },
  {
    email: 'shirley.howard@example.com',
    username: 'shirleyh',
    password: 'shirley123',
  },
  {
    email: 'jonathan.ward@example.com',
    username: 'jonathanw',
    password: 'jonathan456',
  },
  {
    email: 'angela.torres@example.com',
    username: 'angelat',
    password: 'angela789',
  },
  {
    email: 'stephen.peterson@example.com',
    username: 'stephenp',
    password: 'stephen123',
  },
  {
    email: 'anna.gray@example.com',
    username: 'annag',
    password: 'anna456',
  },
  {
    email: 'larry.ramirez@example.com',
    username: 'larryr',
    password: 'larry789',
  },
  {
    email: 'brenda.james@example.com',
    username: 'brendaj',
    password: 'brenda123',
  },
  {
    email: 'justin.watson@example.com',
    username: 'justinw',
    password: 'justin456',
  },
  {
    email: 'pamela.brooks@example.com',
    username: 'pamelab',
    password: 'pamela789',
  },
  {
    email: 'scott.kelly@example.com',
    username: 'scottk',
    password: 'scott123',
  },
  {
    email: 'nicole.sanders@example.com',
    username: 'nicoles',
    password: 'nicole456',
  },
  {
    email: 'brandon.price@example.com',
    username: 'brandonp',
    password: 'brandon789',
  },
  {
    email: 'katherine.bennett@example.com',
    username: 'katherineb',
    password: 'katherine123',
  },
  {
    email: 'samuel.wood@example.com',
    username: 'samuelw',
    password: 'samuel456',
  },
  {
    email: 'christine.barnes@example.com',
    username: 'christineb',
    password: 'christine789',
  },
  {
    email: 'benjamin.ross@example.com',
    username: 'benjaminr',
    password: 'benjamin123',
  },
  {
    email: 'catherine.henderson@example.com',
    username: 'catherineh',
    password: 'catherine456',
  },
  {
    email: 'raymond.coleman@example.com',
    username: 'raymondc',
    password: 'raymond789',
  },
  {
    email: 'debra.jenkins@example.com',
    username: 'debraj',
    password: 'debra123',
  },
  {
    email: 'gregory.perry@example.com',
    username: 'gregoryp',
    password: 'gregory456',
  },
  {
    email: 'rachel.powell@example.com',
    username: 'rachelp',
    password: 'rachel789',
  },
  {
    email: 'alexander.long@example.com',
    username: 'alexanderl',
    password: 'alexander123',
  },
  {
    email: 'janet.patterson@example.com',
    username: 'janetp',
    password: 'janet456',
  },
  {
    email: 'patrick.hughes@example.com',
    username: 'patrickh',
    password: 'patrick789',
  },
  {
    email: 'virginia.flores@example.com',
    username: 'virginiaf',
    password: 'virginia123',
  },
  {
    email: 'frank.washington@example.com',
    username: 'frankw',
    password: 'frank456',
  },
  {
    email: 'carolyn.butler@example.com',
    username: 'carolynb',
    password: 'carolyn789',
  },
  {
    email: 'jack.simmons@example.com',
    username: 'jacks',
    password: 'jack123',
  },
  {
    email: 'frances.foster@example.com',
    username: 'francesf',
    password: 'frances456',
  },
  {
    email: 'dennis.gonzales@example.com',
    username: 'dennisg',
    password: 'dennis789',
  },
  {
    email: 'marie.bryant@example.com',
    username: 'marieb',
    password: 'marie123',
  },
  {
    email: 'jerry.alexander@example.com',
    username: 'jerrya',
    password: 'jerry456',
  },
  {
    email: 'diana.russell@example.com',
    username: 'dianar',
    password: 'diana789',
  },
  {
    email: 'tyler.griffin@example.com',
    username: 'tylerg',
    password: 'tyler123',
  },
  {
    email: 'joyce.diaz@example.com',
    username: 'joyced',
    password: 'joyce456',
  },
];
/**
 * ~100 items for testing
 * */
export const itemsData = [
  {
    name: 'Vintage Leather Jacket',
    description: 'Classic brown leather jacket from the 1970s in excellent condition',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Antique Pocket Watch',
    description: 'Gold-plated pocket watch with intricate engravings, fully functional',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Gaming Laptop',
    description: 'High-performance gaming laptop with RTX 3070 and 32GB RAM',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Signed Baseball',
    description: 'Baseball signed by Babe Ruth, authenticated with certificate',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Oil Painting',
    description: 'Original oil painting of mountain landscape by local artist',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Diamond Necklace',
    description: 'Elegant diamond necklace with 18k white gold chain',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Rare Comic Book',
    description: 'Amazing Fantasy #15 first appearance of Spider-Man, graded 7.0',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Vintage Guitar',
    description: '1965 Fender Stratocaster in sunburst finish with original case',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Smart Watch',
    description: 'Latest model smartwatch with health tracking and GPS',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Antique Desk',
    description: 'Victorian-era mahogany writing desk with ornate carvings',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Camera Lens',
    description: 'Canon EF 70-200mm f/2.8L IS III USM professional lens',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Persian Rug',
    description: 'Hand-woven Persian rug, 8x10 feet, traditional design',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Drone with 4K Camera',
    description: 'Professional quadcopter drone with 4K video recording',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'First Edition Book',
    description: 'First edition of To Kill a Mockingbird in dust jacket',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Mountain Bike',
    description: 'Carbon fiber mountain bike with full suspension',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Vinyl Record Collection',
    description: 'Collection of 50 classic rock vinyl records from the 60s-70s',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Designer Handbag',
    description: 'Authentic Louis Vuitton Neverfull MM tote bag',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Espresso Machine',
    description: 'Commercial-grade espresso machine for home use',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Rare Coins Set',
    description: 'Set of rare US silver dollars from 1880-1900',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Gaming Console',
    description: 'PlayStation 5 with two controllers and 5 games',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Telescope',
    description: 'Celestron NexStar 8SE computerized telescope',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Mechanical Keyboard',
    description: 'Custom mechanical keyboard with Cherry MX switches',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Leather Briefcase',
    description: 'Italian leather briefcase with brass hardware',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Electric Guitar',
    description: 'Gibson Les Paul Standard electric guitar',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Fitness Tracker',
    description: 'Waterproof fitness tracker with heart rate monitor',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Antique Clock',
    description: 'French mantel clock from 1890s with bronze finish',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Snowboard',
    description: 'Burton Custom snowboard with bindings',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Art Deco Lamp',
    description: 'Original 1920s Art Deco table lamp with glass shade',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Blu-ray Collection',
    description: 'Complete Marvel Cinematic Universe Blu-ray collection',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Camping Tent',
    description: '6-person waterproof camping tent with rain fly',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Stamp Collection',
    description: 'Rare stamp collection from various countries, 19th century',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Kayak',
    description: 'Two-person inflatable kayak with paddles and pump',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Projector',
    description: '4K home theater projector with 3000 lumens',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Samurai Sword',
    description: 'Authentic Japanese katana from Edo period with certificate',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Standing Desk',
    description: 'Electric height-adjustable standing desk, 60x30 inches',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Turntable',
    description: 'Audio-Technica AT-LP120 direct-drive turntable',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Bronze Sculpture',
    description: 'Limited edition bronze sculpture by contemporary artist',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Electric Scooter',
    description: 'High-speed electric scooter with 40-mile range',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Chef Knife Set',
    description: 'Professional Japanese chef knife set with wooden block',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Vintage Typewriter',
    description: 'Royal Quiet De Luxe typewriter from 1950s, working condition',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Yoga Mat Set',
    description: 'Premium yoga mat with blocks, strap, and carrying bag',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Model Train Set',
    description: 'HO scale model train set with tracks and scenery',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Leather Watch',
    description: 'Swiss automatic watch with leather band and sapphire crystal',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Pool Table',
    description: '8-foot slate pool table with accessories',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Headphones',
    description: 'Sony WH-1000XM5 noise-cancelling wireless headphones',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Wine Collection',
    description: 'Collection of 12 bottles of vintage Bordeaux wines',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Golf Clubs',
    description: 'Complete set of Callaway golf clubs with bag',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Synthesizer',
    description: 'Moog Sub 37 analog synthesizer with case',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Binoculars',
    description: 'Professional birdwatching binoculars, 10x42 magnification',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Pottery Set',
    description: 'Hand-thrown ceramic dinnerware set for 8 people',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Digital Piano',
    description: 'Yamaha Clavinova digital piano with 88 weighted keys',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Fountain Pen',
    description: 'Montblanc Meisterstück fountain pen with gold nib',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Arcade Machine',
    description: 'Restored vintage Pac-Man arcade machine, fully working',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Cookware Set',
    description: 'All-Clad stainless steel cookware set, 10 pieces',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Emerald Ring',
    description: 'Colombian emerald ring set in platinum with diamond accents',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Leather Sofa',
    description: 'Italian leather three-seater sofa in cognac color',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Fishing Rod Set',
    description: 'Professional fly fishing rod and reel combo',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Movie Poster',
    description: 'Original theatrical poster from Star Wars (1977)',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Skateboard',
    description: 'Custom skateboard with premium trucks and wheels',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Crystal Chandelier',
    description: 'Waterford crystal chandelier with 12 lights',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Boxing Gloves',
    description: 'Professional Everlast boxing gloves, 16oz, signed by Muhammad Ali',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Telescope Lens',
    description: 'Meade 2-inch eyepiece set for deep sky observation',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Barbecue Grill',
    description: 'Weber Genesis gas grill with side burner',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Microscope',
    description: 'Research-grade compound microscope with digital camera',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Silk Scarf',
    description: 'Hermès silk scarf with horse pattern',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Action Figure Set',
    description: 'Complete set of original Star Wars action figures from 1977-1985',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Rowing Machine',
    description: 'Concept2 Model D indoor rowing machine',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Acoustic Guitar',
    description: 'Martin D-28 acoustic guitar with hardshell case',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Coffee Table',
    description: 'Mid-century modern coffee table in walnut',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Air Purifier',
    description: 'Dyson Pure Cool air purifier and fan',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Grandfather Clock',
    description: 'Howard Miller grandfather clock with Westminster chimes',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Metal Detector',
    description: 'Minelab metal detector with pinpointer',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Jade Figurine',
    description: 'Antique Chinese jade dragon figurine from Qing Dynasty',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Electric Bike',
    description: 'RadPower electric bike with 50-mile range',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Tool Set',
    description: 'Professional mechanic tool set with rolling cabinet',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Persian Miniature',
    description: 'Hand-painted Persian miniature artwork on ivory',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Wetsuit',
    description: 'ONeill full wetsuit 4/3mm for surfing',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Bookshelf',
    description: 'Solid oak bookshelf, 6 feet tall with adjustable shelves',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Drum Set',
    description: 'Pearl Export 5-piece drum set with cymbals and hardware',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Zodiac Pendant',
    description: 'Diamond-encrusted zodiac pendant in 14k gold',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Kimono',
    description: 'Vintage Japanese silk kimono with elaborate embroidery',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Blender',
    description: 'Vitamix professional-grade blender with multiple containers',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Map Collection',
    description: 'Antique map collection of American territories from 1800s',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-16T19:56:36.135Z',
  },
  {
    name: 'Racing Wheel',
    description: 'Logitech G923 racing wheel with pedals for gaming',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Taxidermy Display',
    description: 'Victorian-era taxidermy fox in glass display case',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Hookah Set',
    description: 'Traditional Egyptian brass hookah with accessories',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Fossil',
    description: 'Authenticated Tyrannosaurus Rex tooth fossil',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Juicer',
    description: 'Breville cold-press juicer with multiple speed settings',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Massage Chair',
    description: 'Zero-gravity massage chair with heat therapy',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-14T19:56:36.135Z',
  },
  {
    name: 'Samurai Armor',
    description: 'Replica samurai armor with helmet and stand',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
  {
    name: 'Vase',
    description: 'Ming Dynasty ceramic vase with blue and white pattern',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Inflatable Boat',
    description: 'Four-person inflatable boat with motor mount',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-12T19:56:36.135Z',
  },
  {
    name: 'Barometer',
    description: 'Antique brass ship barometer from 1920s',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-13T19:56:36.135Z',
  },
  {
    name: 'Whiskey Decanter Set',
    description: 'Crystal whiskey decanter with six glasses',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Observatory Dome',
    description: 'Personal backyard observatory dome, 10-foot diameter',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-17T19:56:36.135Z',
  },
  {
    name: 'Unicycle',
    description: 'Professional 20-inch unicycle for performance',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-11T19:56:36.135Z',
  },
  {
    name: 'Tarot Card Deck',
    description: 'Antique hand-painted tarot card deck from 1890s',
    starting_bid: 10,
    current_bid: 10,
    end_time: '2026-07-15T19:56:36.135Z',
  },
];
